
-- Generated by Gemini
-- Generation Time: 2025-11-20 14:00:00

-- roles table
CREATE TABLE roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- users table
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    role_id BIGINT,
    status VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- customers table
CREATE TABLE customers (
    id BIGINT PRIMARY KEY,
    customer_code VARCHAR(255),
    name VARCHAR(255),
    address VARCHAR(255),
    contact_info VARCHAR(255),
    tax_code VARCHAR(255),
    description VARCHAR(255),
    company VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (id) REFERENCES users(id)
);

-- employees table
CREATE TABLE employees (
    id BIGINT PRIMARY KEY,
    cccd VARCHAR(255),
    address VARCHAR(255),
    bank_account VARCHAR(255),
    bank_name VARCHAR(255),
    employment_type VARCHAR(255),
    base_salary DOUBLE,
    daily_salary DOUBLE,
    insurance_bhxh DOUBLE,
    insurance_bhyt DOUBLE,
    insurance_bhtn DOUBLE,
    allowance DOUBLE,
    description VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (id) REFERENCES users(id)
);

-- employee_images table
CREATE TABLE employee_images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT,
    image_path VARCHAR(255),
    uploaded_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- services table
CREATE TABLE services (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    price_from DOUBLE,
    price_to DOUBLE,
    main_image VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- service_images table
CREATE TABLE service_images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    service_id BIGINT,
    image_path VARCHAR(255),
    uploaded_at TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES services(id)
);

-- contracts table
CREATE TABLE contracts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT,
    start_date DATE,
    end_date DATE,
    base_price DOUBLE,
    vat DOUBLE,
    total DOUBLE,
    extra_cost DOUBLE,
    discount_cost DOUBLE,
    final_price DOUBLE,
    payment_status VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- contract_services join table
CREATE TABLE contract_services (
    contract_id BIGINT,
    service_id BIGINT,
    PRIMARY KEY (contract_id, service_id),
    FOREIGN KEY (contract_id) REFERENCES contracts(id),
    FOREIGN KEY (service_id) REFERENCES services(id)
);

-- assignments table
CREATE TABLE assignments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT,
    contract_id BIGINT,
    start_date DATE,
    status VARCHAR(255),
    salary_at_time DOUBLE,
    work_days INT,
    description TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (contract_id) REFERENCES contracts(id)
);

-- attendance table
CREATE TABLE attendance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT,
    assignment_id BIGINT,
    date DATE,
    bonus DOUBLE,
    penalty DOUBLE,
    support_cost DOUBLE,
    work_hours DOUBLE,
    is_overtime BOOLEAN,
    overtime_amount DOUBLE,
    approved_by BIGINT,
    description TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (assignment_id) REFERENCES assignments(id),
    FOREIGN KEY (approved_by) REFERENCES users(id)
);

-- materials table
CREATE TABLE materials (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    unit VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- material_distributions table
CREATE TABLE material_distributions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT,
    material_id BIGINT,
    quantity DOUBLE,
    price_at_time DOUBLE,
    date DATE,
    manager_id BIGINT,
    description TEXT,
    created_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (material_id) REFERENCES materials(id),
    FOREIGN KEY (manager_id) REFERENCES users(id)
);

-- payrolls table
CREATE TABLE payrolls (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT,
    total_days INT,
    salary_base DOUBLE,
    bonus_total DOUBLE,
    penalty_total DOUBLE,
    advance_total DOUBLE,
    allowance_total DOUBLE,
    insurance_total DOUBLE,
    final_salary DOUBLE,
    is_paid BOOLEAN,
    payment_date TIMESTAMP,
    accountant_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (accountant_id) REFERENCES users(id)
);

-- ratings table
CREATE TABLE ratings (
    id BIGINT PRIMARY KEY,
    customer_id BIGINT,
    service_id BIGINT,
    rating INT,
    comment TEXT,
    created_at TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (service_id) REFERENCES services(id)
);
